# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import geo_pb2 as geo__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in geo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeoDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/geo.GeoDataService/Health',
                request_serializer=geo__pb2.HealthRequest.SerializeToString,
                response_deserializer=geo__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.EnrichPolygon = channel.unary_unary(
                '/geo.GeoDataService/EnrichPolygon',
                request_serializer=geo__pb2.PolygonRequest.SerializeToString,
                response_deserializer=geo__pb2.EnrichmentResponse.FromString,
                _registered_method=True)
        self.EnsureUserProject = channel.unary_unary(
                '/geo.GeoDataService/EnsureUserProject',
                request_serializer=geo__pb2.EnsureUserProjectRequest.SerializeToString,
                response_deserializer=geo__pb2.ProjectResponse.FromString,
                _registered_method=True)
        self.ListUserProjects = channel.unary_unary(
                '/geo.GeoDataService/ListUserProjects',
                request_serializer=geo__pb2.ListUserProjectsRequest.SerializeToString,
                response_deserializer=geo__pb2.ListUserProjectsResponse.FromString,
                _registered_method=True)
        self.CheckProjectAccess = channel.unary_unary(
                '/geo.GeoDataService/CheckProjectAccess',
                request_serializer=geo__pb2.CheckProjectAccessRequest.SerializeToString,
                response_deserializer=geo__pb2.CheckProjectAccessResponse.FromString,
                _registered_method=True)
        self.CreateProject = channel.unary_unary(
                '/geo.GeoDataService/CreateProject',
                request_serializer=geo__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=geo__pb2.CreateProjectResponse.FromString,
                _registered_method=True)
        self.DeleteProject = channel.unary_unary(
                '/geo.GeoDataService/DeleteProject',
                request_serializer=geo__pb2.DeleteProjectRequest.SerializeToString,
                response_deserializer=geo__pb2.DeleteProjectResponse.FromString,
                _registered_method=True)
        self.AddProjectMember = channel.unary_unary(
                '/geo.GeoDataService/AddProjectMember',
                request_serializer=geo__pb2.AddProjectMemberRequest.SerializeToString,
                response_deserializer=geo__pb2.ProjectMemberResponse.FromString,
                _registered_method=True)
        self.RemoveProjectMember = channel.unary_unary(
                '/geo.GeoDataService/RemoveProjectMember',
                request_serializer=geo__pb2.RemoveProjectMemberRequest.SerializeToString,
                response_deserializer=geo__pb2.ProjectMemberResponse.FromString,
                _registered_method=True)
        self.ListProjectMembers = channel.unary_unary(
                '/geo.GeoDataService/ListProjectMembers',
                request_serializer=geo__pb2.ListProjectMembersRequest.SerializeToString,
                response_deserializer=geo__pb2.ListProjectMembersResponse.FromString,
                _registered_method=True)
        self.PromoteProjectOwner = channel.unary_unary(
                '/geo.GeoDataService/PromoteProjectOwner',
                request_serializer=geo__pb2.PromoteProjectOwnerRequest.SerializeToString,
                response_deserializer=geo__pb2.ProjectMemberResponse.FromString,
                _registered_method=True)
        self.AddCustomPOI = channel.unary_unary(
                '/geo.GeoDataService/AddCustomPOI',
                request_serializer=geo__pb2.AddCustomPOIRequest.SerializeToString,
                response_deserializer=geo__pb2.CustomPOIResponse.FromString,
                _registered_method=True)
        self.UpdateCustomPOI = channel.unary_unary(
                '/geo.GeoDataService/UpdateCustomPOI',
                request_serializer=geo__pb2.UpdateCustomPOIRequest.SerializeToString,
                response_deserializer=geo__pb2.CustomPOIResponse.FromString,
                _registered_method=True)
        self.DeleteCustomPOI = channel.unary_unary(
                '/geo.GeoDataService/DeleteCustomPOI',
                request_serializer=geo__pb2.DeleteCustomPOIRequest.SerializeToString,
                response_deserializer=geo__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListCustomPOIs = channel.unary_unary(
                '/geo.GeoDataService/ListCustomPOIs',
                request_serializer=geo__pb2.ListCustomPOIsRequest.SerializeToString,
                response_deserializer=geo__pb2.ListCustomPOIsResponse.FromString,
                _registered_method=True)
        self.AddCustomArea = channel.unary_unary(
                '/geo.GeoDataService/AddCustomArea',
                request_serializer=geo__pb2.AddCustomAreaRequest.SerializeToString,
                response_deserializer=geo__pb2.CustomAreaResponse.FromString,
                _registered_method=True)
        self.UpdateCustomArea = channel.unary_unary(
                '/geo.GeoDataService/UpdateCustomArea',
                request_serializer=geo__pb2.UpdateCustomAreaRequest.SerializeToString,
                response_deserializer=geo__pb2.CustomAreaResponse.FromString,
                _registered_method=True)
        self.DeleteCustomArea = channel.unary_unary(
                '/geo.GeoDataService/DeleteCustomArea',
                request_serializer=geo__pb2.DeleteCustomAreaRequest.SerializeToString,
                response_deserializer=geo__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListCustomAreas = channel.unary_unary(
                '/geo.GeoDataService/ListCustomAreas',
                request_serializer=geo__pb2.ListCustomAreasRequest.SerializeToString,
                response_deserializer=geo__pb2.ListCustomAreasResponse.FromString,
                _registered_method=True)
        self.ListIntersectingAreas = channel.unary_unary(
                '/geo.GeoDataService/ListIntersectingAreas',
                request_serializer=geo__pb2.PolygonRequest.SerializeToString,
                response_deserializer=geo__pb2.ListCustomAreasResponse.FromString,
                _registered_method=True)
        self.AddRoute = channel.unary_unary(
                '/geo.GeoDataService/AddRoute',
                request_serializer=geo__pb2.AddRouteRequest.SerializeToString,
                response_deserializer=geo__pb2.RouteResponse.FromString,
                _registered_method=True)
        self.ListRoutes = channel.unary_unary(
                '/geo.GeoDataService/ListRoutes',
                request_serializer=geo__pb2.ListRoutesRequest.SerializeToString,
                response_deserializer=geo__pb2.ListRoutesResponse.FromString,
                _registered_method=True)
        self.DeleteRoute = channel.unary_unary(
                '/geo.GeoDataService/DeleteRoute',
                request_serializer=geo__pb2.DeleteRouteRequest.SerializeToString,
                response_deserializer=geo__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.UploadSource = channel.unary_unary(
                '/geo.GeoDataService/UploadSource',
                request_serializer=geo__pb2.UploadSourceRequest.SerializeToString,
                response_deserializer=geo__pb2.UploadSourceResponse.FromString,
                _registered_method=True)
        self.ListUploadedSources = channel.unary_unary(
                '/geo.GeoDataService/ListUploadedSources',
                request_serializer=geo__pb2.ListUploadedSourcesRequest.SerializeToString,
                response_deserializer=geo__pb2.ListUploadedSourcesResponse.FromString,
                _registered_method=True)
        self.DeleteUploadedSource = channel.unary_unary(
                '/geo.GeoDataService/DeleteUploadedSource',
                request_serializer=geo__pb2.DeleteUploadedSourceRequest.SerializeToString,
                response_deserializer=geo__pb2.DeleteResponse.FromString,
                _registered_method=True)


class GeoDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrichPolygon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnsureUserProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUserProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckProjectAccess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProjectMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveProjectMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProjectMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteProjectOwner(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCustomPOI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCustomPOI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCustomPOI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCustomPOIs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCustomArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCustomArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCustomArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCustomAreas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIntersectingAreas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoutes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadSource(self, request, context):
        """Uploaded datasources (in-memory, future: persistent DB)
        TODO: add authentication check when auth is implemented
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUploadedSources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUploadedSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeoDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=geo__pb2.HealthRequest.FromString,
                    response_serializer=geo__pb2.HealthResponse.SerializeToString,
            ),
            'EnrichPolygon': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichPolygon,
                    request_deserializer=geo__pb2.PolygonRequest.FromString,
                    response_serializer=geo__pb2.EnrichmentResponse.SerializeToString,
            ),
            'EnsureUserProject': grpc.unary_unary_rpc_method_handler(
                    servicer.EnsureUserProject,
                    request_deserializer=geo__pb2.EnsureUserProjectRequest.FromString,
                    response_serializer=geo__pb2.ProjectResponse.SerializeToString,
            ),
            'ListUserProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUserProjects,
                    request_deserializer=geo__pb2.ListUserProjectsRequest.FromString,
                    response_serializer=geo__pb2.ListUserProjectsResponse.SerializeToString,
            ),
            'CheckProjectAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckProjectAccess,
                    request_deserializer=geo__pb2.CheckProjectAccessRequest.FromString,
                    response_serializer=geo__pb2.CheckProjectAccessResponse.SerializeToString,
            ),
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=geo__pb2.CreateProjectRequest.FromString,
                    response_serializer=geo__pb2.CreateProjectResponse.SerializeToString,
            ),
            'DeleteProject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProject,
                    request_deserializer=geo__pb2.DeleteProjectRequest.FromString,
                    response_serializer=geo__pb2.DeleteProjectResponse.SerializeToString,
            ),
            'AddProjectMember': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProjectMember,
                    request_deserializer=geo__pb2.AddProjectMemberRequest.FromString,
                    response_serializer=geo__pb2.ProjectMemberResponse.SerializeToString,
            ),
            'RemoveProjectMember': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveProjectMember,
                    request_deserializer=geo__pb2.RemoveProjectMemberRequest.FromString,
                    response_serializer=geo__pb2.ProjectMemberResponse.SerializeToString,
            ),
            'ListProjectMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProjectMembers,
                    request_deserializer=geo__pb2.ListProjectMembersRequest.FromString,
                    response_serializer=geo__pb2.ListProjectMembersResponse.SerializeToString,
            ),
            'PromoteProjectOwner': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteProjectOwner,
                    request_deserializer=geo__pb2.PromoteProjectOwnerRequest.FromString,
                    response_serializer=geo__pb2.ProjectMemberResponse.SerializeToString,
            ),
            'AddCustomPOI': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCustomPOI,
                    request_deserializer=geo__pb2.AddCustomPOIRequest.FromString,
                    response_serializer=geo__pb2.CustomPOIResponse.SerializeToString,
            ),
            'UpdateCustomPOI': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCustomPOI,
                    request_deserializer=geo__pb2.UpdateCustomPOIRequest.FromString,
                    response_serializer=geo__pb2.CustomPOIResponse.SerializeToString,
            ),
            'DeleteCustomPOI': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCustomPOI,
                    request_deserializer=geo__pb2.DeleteCustomPOIRequest.FromString,
                    response_serializer=geo__pb2.DeleteResponse.SerializeToString,
            ),
            'ListCustomPOIs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCustomPOIs,
                    request_deserializer=geo__pb2.ListCustomPOIsRequest.FromString,
                    response_serializer=geo__pb2.ListCustomPOIsResponse.SerializeToString,
            ),
            'AddCustomArea': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCustomArea,
                    request_deserializer=geo__pb2.AddCustomAreaRequest.FromString,
                    response_serializer=geo__pb2.CustomAreaResponse.SerializeToString,
            ),
            'UpdateCustomArea': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCustomArea,
                    request_deserializer=geo__pb2.UpdateCustomAreaRequest.FromString,
                    response_serializer=geo__pb2.CustomAreaResponse.SerializeToString,
            ),
            'DeleteCustomArea': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCustomArea,
                    request_deserializer=geo__pb2.DeleteCustomAreaRequest.FromString,
                    response_serializer=geo__pb2.DeleteResponse.SerializeToString,
            ),
            'ListCustomAreas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCustomAreas,
                    request_deserializer=geo__pb2.ListCustomAreasRequest.FromString,
                    response_serializer=geo__pb2.ListCustomAreasResponse.SerializeToString,
            ),
            'ListIntersectingAreas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIntersectingAreas,
                    request_deserializer=geo__pb2.PolygonRequest.FromString,
                    response_serializer=geo__pb2.ListCustomAreasResponse.SerializeToString,
            ),
            'AddRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRoute,
                    request_deserializer=geo__pb2.AddRouteRequest.FromString,
                    response_serializer=geo__pb2.RouteResponse.SerializeToString,
            ),
            'ListRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoutes,
                    request_deserializer=geo__pb2.ListRoutesRequest.FromString,
                    response_serializer=geo__pb2.ListRoutesResponse.SerializeToString,
            ),
            'DeleteRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRoute,
                    request_deserializer=geo__pb2.DeleteRouteRequest.FromString,
                    response_serializer=geo__pb2.DeleteResponse.SerializeToString,
            ),
            'UploadSource': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadSource,
                    request_deserializer=geo__pb2.UploadSourceRequest.FromString,
                    response_serializer=geo__pb2.UploadSourceResponse.SerializeToString,
            ),
            'ListUploadedSources': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUploadedSources,
                    request_deserializer=geo__pb2.ListUploadedSourcesRequest.FromString,
                    response_serializer=geo__pb2.ListUploadedSourcesResponse.SerializeToString,
            ),
            'DeleteUploadedSource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUploadedSource,
                    request_deserializer=geo__pb2.DeleteUploadedSourceRequest.FromString,
                    response_serializer=geo__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'geo.GeoDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('geo.GeoDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeoDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/Health',
            geo__pb2.HealthRequest.SerializeToString,
            geo__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrichPolygon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/EnrichPolygon',
            geo__pb2.PolygonRequest.SerializeToString,
            geo__pb2.EnrichmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnsureUserProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/EnsureUserProject',
            geo__pb2.EnsureUserProjectRequest.SerializeToString,
            geo__pb2.ProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUserProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/ListUserProjects',
            geo__pb2.ListUserProjectsRequest.SerializeToString,
            geo__pb2.ListUserProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckProjectAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/CheckProjectAccess',
            geo__pb2.CheckProjectAccessRequest.SerializeToString,
            geo__pb2.CheckProjectAccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/CreateProject',
            geo__pb2.CreateProjectRequest.SerializeToString,
            geo__pb2.CreateProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/DeleteProject',
            geo__pb2.DeleteProjectRequest.SerializeToString,
            geo__pb2.DeleteProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddProjectMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/AddProjectMember',
            geo__pb2.AddProjectMemberRequest.SerializeToString,
            geo__pb2.ProjectMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveProjectMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/RemoveProjectMember',
            geo__pb2.RemoveProjectMemberRequest.SerializeToString,
            geo__pb2.ProjectMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProjectMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/ListProjectMembers',
            geo__pb2.ListProjectMembersRequest.SerializeToString,
            geo__pb2.ListProjectMembersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteProjectOwner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/PromoteProjectOwner',
            geo__pb2.PromoteProjectOwnerRequest.SerializeToString,
            geo__pb2.ProjectMemberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCustomPOI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/AddCustomPOI',
            geo__pb2.AddCustomPOIRequest.SerializeToString,
            geo__pb2.CustomPOIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCustomPOI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/UpdateCustomPOI',
            geo__pb2.UpdateCustomPOIRequest.SerializeToString,
            geo__pb2.CustomPOIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCustomPOI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/DeleteCustomPOI',
            geo__pb2.DeleteCustomPOIRequest.SerializeToString,
            geo__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCustomPOIs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/ListCustomPOIs',
            geo__pb2.ListCustomPOIsRequest.SerializeToString,
            geo__pb2.ListCustomPOIsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCustomArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/AddCustomArea',
            geo__pb2.AddCustomAreaRequest.SerializeToString,
            geo__pb2.CustomAreaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCustomArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/UpdateCustomArea',
            geo__pb2.UpdateCustomAreaRequest.SerializeToString,
            geo__pb2.CustomAreaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCustomArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/DeleteCustomArea',
            geo__pb2.DeleteCustomAreaRequest.SerializeToString,
            geo__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCustomAreas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/ListCustomAreas',
            geo__pb2.ListCustomAreasRequest.SerializeToString,
            geo__pb2.ListCustomAreasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIntersectingAreas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/ListIntersectingAreas',
            geo__pb2.PolygonRequest.SerializeToString,
            geo__pb2.ListCustomAreasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/AddRoute',
            geo__pb2.AddRouteRequest.SerializeToString,
            geo__pb2.RouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/ListRoutes',
            geo__pb2.ListRoutesRequest.SerializeToString,
            geo__pb2.ListRoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/DeleteRoute',
            geo__pb2.DeleteRouteRequest.SerializeToString,
            geo__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/UploadSource',
            geo__pb2.UploadSourceRequest.SerializeToString,
            geo__pb2.UploadSourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUploadedSources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/ListUploadedSources',
            geo__pb2.ListUploadedSourcesRequest.SerializeToString,
            geo__pb2.ListUploadedSourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUploadedSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/DeleteUploadedSource',
            geo__pb2.DeleteUploadedSourceRequest.SerializeToString,
            geo__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
