# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import geo_pb2 as geo__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in geo_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GeoDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/geo.GeoDataService/Health',
                request_serializer=geo__pb2.HealthRequest.SerializeToString,
                response_deserializer=geo__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.EnrichPolygon = channel.unary_unary(
                '/geo.GeoDataService/EnrichPolygon',
                request_serializer=geo__pb2.PolygonRequest.SerializeToString,
                response_deserializer=geo__pb2.EnrichmentResponse.FromString,
                _registered_method=True)
        self.AddCustomPOI = channel.unary_unary(
                '/geo.GeoDataService/AddCustomPOI',
                request_serializer=geo__pb2.AddCustomPOIRequest.SerializeToString,
                response_deserializer=geo__pb2.CustomPOIResponse.FromString,
                _registered_method=True)
        self.UpdateCustomPOI = channel.unary_unary(
                '/geo.GeoDataService/UpdateCustomPOI',
                request_serializer=geo__pb2.UpdateCustomPOIRequest.SerializeToString,
                response_deserializer=geo__pb2.CustomPOIResponse.FromString,
                _registered_method=True)
        self.DeleteCustomPOI = channel.unary_unary(
                '/geo.GeoDataService/DeleteCustomPOI',
                request_serializer=geo__pb2.DeleteCustomPOIRequest.SerializeToString,
                response_deserializer=geo__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListCustomPOIs = channel.unary_unary(
                '/geo.GeoDataService/ListCustomPOIs',
                request_serializer=geo__pb2.ListCustomPOIsRequest.SerializeToString,
                response_deserializer=geo__pb2.ListCustomPOIsResponse.FromString,
                _registered_method=True)
        self.AddCustomArea = channel.unary_unary(
                '/geo.GeoDataService/AddCustomArea',
                request_serializer=geo__pb2.AddCustomAreaRequest.SerializeToString,
                response_deserializer=geo__pb2.CustomAreaResponse.FromString,
                _registered_method=True)
        self.UpdateCustomArea = channel.unary_unary(
                '/geo.GeoDataService/UpdateCustomArea',
                request_serializer=geo__pb2.UpdateCustomAreaRequest.SerializeToString,
                response_deserializer=geo__pb2.CustomAreaResponse.FromString,
                _registered_method=True)
        self.DeleteCustomArea = channel.unary_unary(
                '/geo.GeoDataService/DeleteCustomArea',
                request_serializer=geo__pb2.DeleteCustomAreaRequest.SerializeToString,
                response_deserializer=geo__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.ListCustomAreas = channel.unary_unary(
                '/geo.GeoDataService/ListCustomAreas',
                request_serializer=geo__pb2.ListCustomAreasRequest.SerializeToString,
                response_deserializer=geo__pb2.ListCustomAreasResponse.FromString,
                _registered_method=True)
        self.AddRoute = channel.unary_unary(
                '/geo.GeoDataService/AddRoute',
                request_serializer=geo__pb2.AddRouteRequest.SerializeToString,
                response_deserializer=geo__pb2.RouteResponse.FromString,
                _registered_method=True)
        self.ListRoutes = channel.unary_unary(
                '/geo.GeoDataService/ListRoutes',
                request_serializer=geo__pb2.ListRoutesRequest.SerializeToString,
                response_deserializer=geo__pb2.ListRoutesResponse.FromString,
                _registered_method=True)
        self.DeleteRoute = channel.unary_unary(
                '/geo.GeoDataService/DeleteRoute',
                request_serializer=geo__pb2.DeleteRouteRequest.SerializeToString,
                response_deserializer=geo__pb2.DeleteResponse.FromString,
                _registered_method=True)


class GeoDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrichPolygon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCustomPOI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCustomPOI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCustomPOI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCustomPOIs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddCustomArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCustomArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCustomArea(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCustomAreas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoutes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRoute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeoDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=geo__pb2.HealthRequest.FromString,
                    response_serializer=geo__pb2.HealthResponse.SerializeToString,
            ),
            'EnrichPolygon': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichPolygon,
                    request_deserializer=geo__pb2.PolygonRequest.FromString,
                    response_serializer=geo__pb2.EnrichmentResponse.SerializeToString,
            ),
            'AddCustomPOI': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCustomPOI,
                    request_deserializer=geo__pb2.AddCustomPOIRequest.FromString,
                    response_serializer=geo__pb2.CustomPOIResponse.SerializeToString,
            ),
            'UpdateCustomPOI': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCustomPOI,
                    request_deserializer=geo__pb2.UpdateCustomPOIRequest.FromString,
                    response_serializer=geo__pb2.CustomPOIResponse.SerializeToString,
            ),
            'DeleteCustomPOI': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCustomPOI,
                    request_deserializer=geo__pb2.DeleteCustomPOIRequest.FromString,
                    response_serializer=geo__pb2.DeleteResponse.SerializeToString,
            ),
            'ListCustomPOIs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCustomPOIs,
                    request_deserializer=geo__pb2.ListCustomPOIsRequest.FromString,
                    response_serializer=geo__pb2.ListCustomPOIsResponse.SerializeToString,
            ),
            'AddCustomArea': grpc.unary_unary_rpc_method_handler(
                    servicer.AddCustomArea,
                    request_deserializer=geo__pb2.AddCustomAreaRequest.FromString,
                    response_serializer=geo__pb2.CustomAreaResponse.SerializeToString,
            ),
            'UpdateCustomArea': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCustomArea,
                    request_deserializer=geo__pb2.UpdateCustomAreaRequest.FromString,
                    response_serializer=geo__pb2.CustomAreaResponse.SerializeToString,
            ),
            'DeleteCustomArea': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCustomArea,
                    request_deserializer=geo__pb2.DeleteCustomAreaRequest.FromString,
                    response_serializer=geo__pb2.DeleteResponse.SerializeToString,
            ),
            'ListCustomAreas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCustomAreas,
                    request_deserializer=geo__pb2.ListCustomAreasRequest.FromString,
                    response_serializer=geo__pb2.ListCustomAreasResponse.SerializeToString,
            ),
            'AddRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRoute,
                    request_deserializer=geo__pb2.AddRouteRequest.FromString,
                    response_serializer=geo__pb2.RouteResponse.SerializeToString,
            ),
            'ListRoutes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoutes,
                    request_deserializer=geo__pb2.ListRoutesRequest.FromString,
                    response_serializer=geo__pb2.ListRoutesResponse.SerializeToString,
            ),
            'DeleteRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRoute,
                    request_deserializer=geo__pb2.DeleteRouteRequest.FromString,
                    response_serializer=geo__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'geo.GeoDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('geo.GeoDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GeoDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/Health',
            geo__pb2.HealthRequest.SerializeToString,
            geo__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrichPolygon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/EnrichPolygon',
            geo__pb2.PolygonRequest.SerializeToString,
            geo__pb2.EnrichmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCustomPOI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/AddCustomPOI',
            geo__pb2.AddCustomPOIRequest.SerializeToString,
            geo__pb2.CustomPOIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCustomPOI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/UpdateCustomPOI',
            geo__pb2.UpdateCustomPOIRequest.SerializeToString,
            geo__pb2.CustomPOIResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCustomPOI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/DeleteCustomPOI',
            geo__pb2.DeleteCustomPOIRequest.SerializeToString,
            geo__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCustomPOIs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/ListCustomPOIs',
            geo__pb2.ListCustomPOIsRequest.SerializeToString,
            geo__pb2.ListCustomPOIsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddCustomArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/AddCustomArea',
            geo__pb2.AddCustomAreaRequest.SerializeToString,
            geo__pb2.CustomAreaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCustomArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/UpdateCustomArea',
            geo__pb2.UpdateCustomAreaRequest.SerializeToString,
            geo__pb2.CustomAreaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCustomArea(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/DeleteCustomArea',
            geo__pb2.DeleteCustomAreaRequest.SerializeToString,
            geo__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCustomAreas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/ListCustomAreas',
            geo__pb2.ListCustomAreasRequest.SerializeToString,
            geo__pb2.ListCustomAreasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/AddRoute',
            geo__pb2.AddRouteRequest.SerializeToString,
            geo__pb2.RouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRoutes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/ListRoutes',
            geo__pb2.ListRoutesRequest.SerializeToString,
            geo__pb2.ListRoutesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geo.GeoDataService/DeleteRoute',
            geo__pb2.DeleteRouteRequest.SerializeToString,
            geo__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
